In [1]:
import numpy as np

# Calcular la matriz de pesos sinápticos usando la regla de Hebb
def calculate_weight_matrix(patterns):
  n_neurons = patterns.shape[1]
  W = np.zeros((n_neurons, n_neurons))
  for p in patterns:
    W += np.outer(p, p)  # Producto externo para cada patrón
  np.fill_diagonal(W, 0)  # Establecer la diagonal en cero (sin autoconexiones)
  W /= patterns.shape[0]  # Normalizar por el número de patrones
  return W

# Actualizar la red de forma secuencial hasta convergencia o máximo de iteraciones
def update_network(state, W, max_iterations):
  states = [state.copy()]  # Guardar el estado inicial
  for _ in range(max_iterations):
    for i in range(len(state)):
      # Calcular la activación para la neurona i
      activation = np.dot(W[i], state)
      # Regla de actualización: función signo
      state[i] = 1 if activation >= 0 else -1
    states.append(state.copy())  # Guardar el estado actual
    # Verificar convergencia
    if np.array_equal(states[-1], states[-2]):
      break
  return states

def hopfield(P1, P2, input_pattern, iterations):
  # Convertir los patrones a arrays de numpy para cálculos matriciales
  P1 = np.array(P1)
  P2 = np.array(P2)
  patterns = np.array([P1, P2])
  input_pattern = np.array(input_pattern)

  # Calcular la matriz de pesos
  W = calculate_weight_matrix(patterns)
  
  # Ejecutar la red con el patrón de entrada
  states = update_network(input_pattern.copy(), W, iterations)
  
  # Mostrar resultados
  print("Matriz de pesos:")
  print(W)
  print("\nPatrón inicial:", input_pattern)
  print("\nEvolución de estados:")
  for i, state in enumerate(states):
    print(f"Paso {i}: {state}")

  # Verificar si el estado final coincide con un patrón almacenado
  final_state = states[-1]
  print("\nEstado final:", final_state)
  if np.array_equal(final_state, P1):
    print("Convergió a P1:", P1)
  elif np.array_equal(final_state, P2):
    print("Convergió a P2:", P2)
  else:
    print("No convergió a un patrón almacenado.")

In [2]:
P1 = [1, -1, 1]
P2 = [-1, 1, -1]
input_pattern = [1, -1, -1]
iterations = 10

hopfield(P1, P2, input_pattern, iterations)

Matriz de pesos:
[[ 0. -1.  1.]
 [-1.  0. -1.]
 [ 1. -1.  0.]]

Patrón inicial: [ 1 -1 -1]

Evolución de estados:
Paso 0: [ 1 -1 -1]
Paso 1: [1 1 1]
Paso 2: [ 1 -1  1]
Paso 3: [ 1 -1  1]

Estado final: [ 1 -1  1]
Convergió a P1: [ 1 -1  1]


In [2]:
import numpy as np

# Calcular la matriz de pesos sinápticos usando la regla de Hebb
def calculate_weight_matrix(patterns):
  n_neurons = patterns.shape[1]
  W = np.zeros((n_neurons, n_neurons))
  for p in patterns:
    W += np.outer(p, p)
  np.fill_diagonal(W, 0)
  W /= patterns.shape[0]
  return W

# Actualizar la red hasta convergencia o máximo de iteraciones
def update_network(state, W, max_iterations):
  states = [state.copy()]
  for _ in range(max_iterations):
    for i in range(len(state)):
      activation = np.dot(W[i], state)
      state[i] = 1 if activation >= 0 else -1
    states.append(state.copy())
    if np.array_equal(states[-1], states[-2]):
      break
  return states

# Función principal que acepta múltiples patrones almacenados y de evaluación
def hopfield(patterns, input_patterns, iterations=10):
  patterns = np.array(patterns)
  input_patterns = [np.array(p) for p in input_patterns]
  
  # Calcular la matriz de pesos
  W = calculate_weight_matrix(patterns)
  
  print("Matriz de pesos:")
  print(W)

  for idx, input_pattern in enumerate(input_patterns):
    print(f"\n🔹 Evaluando patrón {idx+1}: {input_pattern}")
    states = update_network(input_pattern.copy(), W, iterations)
    for i, state in enumerate(states):
      print(f"Paso {i}: {state}")
    
    final_state = states[-1]
    print("Estado final:", final_state)
    # Comprobar si converge a uno de los patrones almacenados
    match = False
    for j, p in enumerate(patterns):
      if np.array_equal(final_state, p):
        print(f"✅ Convergió al patrón almacenado P{j+1}: {p}")
        match = True
        break
    if not match:
      print("⚠️ No convergió a ningún patrón almacenado.")
      

In [4]:
# Ejemplo de uso
stored_patterns = [
  [1, -1, 1, -1],
  [-1, 1, -1, 1],
  [1, 1, -1, -1]
]

evaluation_patterns = [
  [1, -1, -1, -1],
  [-1, -1, -1, 1],
  [1, -1, -1, 1]
]

hopfield(stored_patterns, evaluation_patterns, iterations=10)


Matriz de pesos:
[[ 0.         -0.33333333  0.33333333 -1.        ]
 [-0.33333333  0.         -1.          0.33333333]
 [ 0.33333333 -1.          0.         -0.33333333]
 [-1.          0.33333333 -0.33333333  0.        ]]

🔹 Evaluando patrón 1: [ 1 -1 -1 -1]
Paso 0: [ 1 -1 -1 -1]
Paso 1: [ 1  1 -1 -1]
Paso 2: [ 1  1 -1 -1]
Estado final: [ 1  1 -1 -1]
✅ Convergió al patrón almacenado P3: [ 1  1 -1 -1]

🔹 Evaluando patrón 2: [-1 -1 -1  1]
Paso 0: [-1 -1 -1  1]
Paso 1: [-1  1 -1  1]
Paso 2: [-1  1 -1  1]
Estado final: [-1  1 -1  1]
✅ Convergió al patrón almacenado P2: [-1  1 -1  1]

🔹 Evaluando patrón 3: [ 1 -1 -1  1]
Paso 0: [ 1 -1 -1  1]
Paso 1: [-1  1 -1  1]
Paso 2: [-1  1 -1  1]
Estado final: [-1  1 -1  1]
✅ Convergió al patrón almacenado P2: [-1  1 -1  1]


In [3]:
# Ejemplo de uso
stored_patterns = [
  [1, 1, -1, -1],
  [-1, -1, 1, 1]
]

evaluation_patterns = [
  [1, -1, -1, -1]
]

hopfield(stored_patterns, evaluation_patterns, 10)

Matriz de pesos:
[[ 0.  1. -1. -1.]
 [ 1.  0. -1. -1.]
 [-1. -1.  0.  1.]
 [-1. -1.  1.  0.]]

🔹 Evaluando patrón 1: [ 1 -1 -1 -1]
Paso 0: [ 1 -1 -1 -1]
Paso 1: [ 1  1 -1 -1]
Paso 2: [ 1  1 -1 -1]
Estado final: [ 1  1 -1 -1]
✅ Convergió al patrón almacenado P1: [ 1  1 -1 -1]
